AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      EndpointConfiguration:
        Type: REGIONAL
      
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: .
      Handler: lambda_fn.handler
      Events:
        RootHandler:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /
            Method: ANY
        ProxyHandler:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY