AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a 2 zone flat VPC with no NAT gateways"

Parameters:

    VpcCidr:
        Type: String
        Default: 10.0.0.0/16

Resources:

    Vpc:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: !Ref VpcCidr

    Subnet1:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}a"
            CidrBlock: !Select [ 0, !Cidr [ !GetAtt Vpc.CidrBlock, 1, 8 ]]
            VpcId: !Ref Vpc
            Tags:
              - Key: Name
                Value: !Sub "${AWS::StackName}-${AWS::Region}a"
    
    Subnet2:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}b"
            CidrBlock: !Select [ 0, !Cidr [ !GetAtt Vpc.CidrBlock, 2, 8 ]]
            VpcId: !Ref Vpc
            Tags:
              - Key: Name
                Value: !Sub "${AWS::StackName}-${AWS::Region}b"

    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties: {}

    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties: 
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref Vpc

    RouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref Vpc

    EgressRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref RouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    SubnetRouteTableAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref Subnet1
            RouteTableId: !Ref RouteTable

    SubnetRouteTableAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref Subnet2
            RouteTableId: !Ref RouteTable